### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by appleinmyface** [appleinmyface/prework-study-guide#3]
JavaScript

As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by Pr-at-ham** [comment]
I suggest you go through w3 school. If I got your issue right then this web-site will help you , if this is what you not want please explain your issue briefly I am happy to help

**Comment by appleinmyface** [comment]
done
